### ISSUE TITLE
Subscription for AvTransport

### ISSUE THREAD

**Issue by wylieswanson** [michaelotto/sonos-monitor#2]
Subscription for AvTransport appears to be no longer working?

**Comment by michaelotto** [comment]
Works for me. Which version of SoCo do you have? (pip show soco 2>/dev/null|grep Version)

**Comment by wylieswanson** [comment]
Metadata-Version: 2.0
Version: 0.11.1

**Comment by wylieswanson** [comment]
Interestingly, when I download and install soco manually (instead of the pip), I see:

Metadata-Version: 1.1
Version: 0.11.1

And it works great.  Thank you
